name: pull_request

on:
  pull_request:
    branches: [master, dev]
env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:

  xcodebuild:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: |
        xcodebuild build -workspace COVIDWatch.xcworkspace -scheme 'COVIDWatch iOS' CODE_SIGNING_ALLOWED=NO

  swiftlint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      run: |
        ./Pods/SwiftLint/swiftlint --strict

  notify_ready_for_review:
    needs: [xcodebuild, swiftlint]
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 'Pull Request: Ready For Review!'
        SLACK_MESSAGE: 'Pull request has passed all quality checks and is ready for review.'
        SLACK_ICON_EMOJI: ':robot:'
        SLACK_USERNAME: 'Github Actions'

  testflight_upload:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup SSH Keys and known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: TestFlight Upload
      run: |
        gem install bundler:1.16.6
        bundle install
        bundle exec fastlane beta
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.TOKEN_FOR_PROFILES }}