name: pull_request

on:
  pull_request:
    branches: [master, dev]
env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:

  xcodebuild:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: |
        gem install bundler:1.16.6
        bundle install
        xcodebuild build -workspace COVIDWatch.xcworkspace -scheme 'COVIDWatch iOS' CODE_SIGNING_ALLOWED=NO | tee xcodebuild.log | xcpretty
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: xcodebuild.log
        path: xcodebuild.log

  swiftlint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      run: |
        ./Pods/SwiftLint/swiftlint --strict 2>&1 | tee swiftlint-violations.log
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: swiftlint-violations.log
        path: swiftlint-violations.log

  testflight_upload:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Github.com to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: TestFlight Upload
      run: |
        gem install bundler:1.16.6
        bundle install
        bundle exec fastlane beta
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.TOKEN_FOR_PROFILES }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
#        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
#        FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}