name: pull_request

on:
  pull_request:
    branches: [master, dev]
env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:

  xcodebuild:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode Build
      run: |
        xcodebuild build -workspace COVIDWatch.xcworkspace -scheme 'COVIDWatch iOS' CODE_SIGNING_ALLOWED=NO

  swiftlint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: SwiftLint
      run: |
        ./Pods/SwiftLint/swiftlint --strict

  testflight_upload:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: TestFlight Upload
      run: |
        gem install bundler:1.16.6
        bundle install
        bundle exec fastlane beta
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: 'A new TestFlight build was uploaded.'
