name: upload_beta

on:
  schedule:
    - cron:  '0 0 * * *'
env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:

  testflight_upload:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add Github.com to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: TestFlight Upload
      run: |
        gem install bundler:1.16.6
        bundle install
        bundle exec fastlane beta
      env:
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.TOKEN_FOR_PROFILES }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
